name: Check Markdown links for modified files

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@master
    - id: link-check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: 'mlc_pull_req_config.json'
        check-modified-files-only: 'yes'
        use-verbose-mode: 'yes'
        base-branch: 'main'
        use-quiet-mode: 'yes'
    - id: summary
      run: |
        echo '# markdown-link-check summary' >> $GITHUB_STEP_SUMMARY
        echo >> $GITHUB_STEP_SUMMARY
        echo 'This Github action is currently in beta, and may incorrectly report broken links. To help us improve this Github action, please report any false negatives, false positives or any other issues by [opening an issue](https://github.com/ipfs/ipfs-docs/issues/new/choose). ' >> $GITHUB_STEP_SUMMARY
        echo '## Job Status: '>> $GITHUB_STEP_SUMMARY
        echo ${{ job.status }} >> $GITHUB_STEP_SUMMARY
        echo '## Results: ' >> $GITHUB_STEP_SUMMARY     
        echo 'To view the results of this GitHub action, do the following:'
        echo '1. Navigate to the ${{ steps.link-check.outputs }}.' >> $GITHUB_STEP_SUMMARY       
        echo '2. In the search field (upper right hand corner), type _MARKDOWN LINK CHECK_. The log jumps to the output of the markdown-link-check action.' >> $GITHUB_STEP_SUMMARY  
        echo '3. Look through the log lines below the _=========================> MARKDOWN LINK CHECK <=========================_ line. ' >> $GITHUB_STEP_SUMMARY  
        echo '   If a dead link was found, it, along with the status code, will be listed below the _ERROR_ line. Find the link in your markdown and fix it.' >> $GITHUB_STEP_SUMMARY  
        echo '**Example:**'
        echo 'ERROR: 1 dead links found!
        echo '[✖] https://givweueerervuvwbeiuv.com#nvruvwrveri → Status: 404
        echo '4. If the action incorrectly identified a link as broken, please copy the log output and '