name: Check Markdown links for modified files

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      uses: actions/checkout@master
    - id: link-check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      continue-on-error: true
      with:
        config-file: 'mlc_pull_req_config.json'
        check-modified-files-only: 'yes'
        use-verbose-mode: 'yes'
        base-branch: 'main'
        use-quiet-mode: 'yes'
    - id: summary
      run: |
        echo '# markdown-link-check summary' >> $GITHUB_STEP_SUMMARY
        echo >> $GITHUB_STEP_SUMMARY
        echo $GITHUB_OUTPUT >> $GITHUB_STEP_SUMMARY
        echo 'Results: ' >> $GITHUB_STEP_SUMMARY       
        echo '${{ steps.link-check.results }}' >> $GITHUB_STEP_SUMMARY       
        echo '# call to action' >> $GITHUB_STEP_SUMMARY
        echo 'This Github action is currently in beta, and may incorrectly report broken links. To help us improve this Github action, please report any false negatives, false positives or any other issues by [opening an issue](https://github.com/ipfs/ipfs-docs/issues/new/choose). ' >> $GITHUB_STEP_SUMMARY
