name: Check Markdown links for modified files

on: [pull_request]

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@master
    - name: link-check
      uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        config-file: 'mlc_pull_req_config.json'
        check-modified-files-only: 'yes'
        use-verbose-mode: 'yes'
        base-branch: 'main'
        continue-on-error: true
    - name: summary
      run: |
        echo '# markdown-link-check summary' >> $GITHUB_STEP_SUMMARY
        echo >> $GITHUB_STEP_SUMMARY
        echo '${{ steps.link-check.outputs }}' >> $GITHUB_STEP_SUMMARY
